### ISSUE TITLE
Fix Favicon loading

### ISSUE THREAD

**Issue by RonanMorgan** [dataforgoodfr/d4g-ansible#13]
![Image](https://github.com/user-attachments/assets/9e675289-dadd-49ea-a245-0b56922411b6)

The Favicon image is added by ansible into the container through a volume : 

```
  app:
    image: ghcr.io/goauthentik/server:2025.2.3
    command: server
    env_file: authentik.env
    volumes:
      - ./branding/logo-dfg.png:/web/dist/assets/icons/icon_left_brand.png # by default it's a .jpg
      - ./branding/favicon.png:/static/dist/assets/icons/d4gicon.png
```

But it's not loaded by the browser as you can see in the above picture
