### ISSUE TITLE
Création d'un outil de test de charge générique

### ISSUE THREAD

**Issue by pagbrl** [dataforgoodfr/d4g-ansible#15]
Il arrive régulièrement que des projets Data for Good recoivent une couverture médiatique conséquente.

Nous préparons au mieux les projets en amont à ces pics ponctuels mais très significatifs de trafic, mais nous cherchons aussi à développer un outil de test qui pourrait être réutilisé de projet en projet.

Les besoins sont assez simples : 
- Simuler un grand nombre de requêtes HTTP sur une page pendant un temps donné
- Obtenir si possible des informations sur le temps de réponse de la page lors de ces tests

Dans le passé nous avons basé certains tests sur l'outil Locust.

**Comment by pagbrl** [comment]
Base très simple trouvée dans mes archives 

```yml
services:
  master:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./locustfile.py.local:/mnt/locust/locustfile.py
    command: -f /mnt/locust/locustfile.py --master -H http://master:8089
    environment:
      PYTHONUNBUFFERED: 1
      LOCUST_MODE: standalone
      LOCUST_OPTS: "--web-port 8089 --loglevel DEBUG"

  worker:
    image: locustio/locust
    volumes:
      - ./locustfile.py.local:/mnt/locust/locustfile.py
    command: -f /mnt/locust/locustfile.py --worker --master-host master
```

```python
from locust import HttpUser, task
import random
import sys
import hashlib
import logging


class QuickstartUser(HttpUser):
    def log(self, message):
        print(message)

    @task
    def hello_world(self):
        url = f"https://example.com"
        response = self.client.get(url)
        logging.info("Request: \n{} {}\nResponse: \nStatus Code {} \nHeaders :{}".format("GET", url,
                                                                                         response.status_code,
                                                                                         response.headers))
```
